name: Update IPC

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  update-ipc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas openpyxl requests

      - name: Run update script
        run: python update_ipc.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ipc.json
          git commit -m "auto: update ipc.json" || echo "No changes to commit"
          git push