name: Update IPC from fedstatAPIr

on:
  schedule:
    - cron: '0 10 * * 0'
  workflow_dispatch:

jobs:
  update-ipc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: Rscript -e 'install.packages("fedstatAPIr", repos="http://cran.r-project.org")'

      - name: Run R script
        run: Rscript update_ipc.R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: pip install pandas

      - name: Run Python update script
        run: python update_ipc.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ipc.json
          git commit -m "auto: update ipc.json from fedstat" || echo "No changes to commit"
          git push